/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgendaRouteImport } from './routes/admin.agenda'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminMateriaisRouteImport } from './routes/admin.materiais'
import { Route as AdminMentoriasRouteImport } from './routes/admin.mentorias'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMateriaisRoute = AdminMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMentoriasRoute = AdminMentoriasRouteImport.update({
  id: '/mentorias',
  path: '/mentorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRoute
  '/auth': typeof AuthRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/mentorias': typeof AdminMentoriasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/auth': typeof AuthRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/mentorias': typeof AdminMentoriasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aluno': typeof AlunoRoute
  '/auth': typeof AuthRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/materiais': typeof AdminMateriaisRoute
  '/admin/mentorias': typeof AdminMentoriasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aluno'
    | '/auth'
    | '/admin/agenda'
    | '/admin/alunos'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/materiais'
    | '/admin/mentorias'
    | '/admin/relatorios'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aluno'
    | '/auth'
    | '/admin/agenda'
    | '/admin/alunos'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/materiais'
    | '/admin/mentorias'
    | '/admin/relatorios'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aluno'
    | '/auth'
    | '/admin/agenda'
    | '/admin/alunos'
    | '/admin/cursos'
    | '/admin/financeiro'
    | '/admin/materiais'
    | '/admin/mentorias'
    | '/admin/relatorios'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlunoRoute: typeof AlunoRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/materiais': {
      id: '/admin/materiais'
      path: '/materiais'
      fullPath: '/admin/materiais'
      preLoaderRoute: typeof AdminMateriaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mentorias': {
      id: '/admin/mentorias'
      path: '/mentorias'
      fullPath: '/admin/mentorias'
      preLoaderRoute: typeof AdminMentoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminMateriaisRoute: typeof AdminMateriaisRoute
  AdminMentoriasRoute: typeof AdminMentoriasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAlunosRoute: AdminAlunosRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminMateriaisRoute: AdminMateriaisRoute,
  AdminMentoriasRoute: AdminMentoriasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AlunoRoute: AlunoRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
